user_name = input("What is your name? ")
a = int(input("Enter the value of variable A:"))
b = int(input("Enter the value of variable B:"))

print (f"A + B = {a+b}")
print (f"A - B = {a-b}")
print (f"A * B = {a*b}")  
print (f"A / B = {a/b}")
print (f"A ** B = {a**b}")
print (f"A // B = {a//b}")
print (f"A % B = {a%b}")