name = input("What is your name?")
print(f'Well, {name}, Let us count a bit \U0001F914')
a = int(input("write first number A:"))
b = int(input("write second number B:"))
print("Here we go \U0001F603:")
print("   A + B =", a+b)
print("   A - B =", a-b)
print("   A * B =", a*b)
print("   A / B =", a/b)
print("   A ** B =", a**b)
print("   A // B =", a//b)
print("   A % B =", a%b)
print("   A ** B + B ** A =", a**b+b**a)
print("  (A ** B + B) ** A =", (a**b+b)**a)