a = int(input("A = "))
b = int(input("B = "))
print("A + B = ", a + b)
print("A - B = ", a - b)
print("A * B = ", a * b)
print("A / B = ", a / b)
print("A**B = ", a**b)
print("A//B = ", a//b)
print("A%B = ", a%b)
