# *** Practical task 1 ***
# Write a game script that randomly generates a number from a range
# of 1 to 100 and asks the user to guess that number in 10 tries.
# The program reads the numbers entered by the user and prompts the user
# whether the guessed number is greater or less than the number entered
# by the user. The game must continue until the user has used 10 attempts
# and guessed the number. If the user guessed the number, the program prints
# a congratulatory message, and if 10 attempts have been exhausted and the user
# did not have time to guess the number, then the corresponding message
# is displayed. (to perform the task, you need to import the random module,
# and from it the randint() function)

from random import randint

user_name = input('Hello! Enter your name: ').capitalize()

MIN_NUMBER, MAX_NUMBER, MAX_ATTEMPT = 1, 100, 10
number = randint(MIN_NUMBER, MAX_NUMBER)

print('The computer has already generated a number! '
      'Let\'s start the \"Number guessing game\".')

attempt, user_number = 1, None
while attempt <= MAX_ATTEMPT:
    print(f'\nAttempt number {attempt}.', end=' ')
    user_number = input(f'Enter your number from range [{MIN_NUMBER}; {MAX_NUMBER}]:\n')

    if user_number.isdigit():
        user_number = int(user_number)
    else:
        print("You must enter a NATURAL NUMBER from the specified range!")
        attempt += 1
        continue

    if user_number == number:
        print(f'\nCongratulations! Dear, {user_name}. You are a winner of the '
              f'\"Number guessing game\"! Number of attempts is {attempt}.')
        break
    elif user_number in range(MIN_NUMBER, MAX_NUMBER + 1) and user_number < number:
        print('The number you entered is SMALLER than the number generated by the computer. Try again)))')
    elif user_number in range(MIN_NUMBER, MAX_NUMBER + 1) and user_number > number:
        print('The number you entered is GREATER than the number generated by the computer. Try again)))')
    else:
        print(f'Your number is not in range {MIN_NUMBER} to {MAX_NUMBER}! Try again')
    attempt += 1

if user_number != number:
    print(f'\nYou used all {MAX_ATTEMPT} attempts '
          f'and did not guess the number generated by the computer '
          f'(this number is {number}). Good luck next time)))')
